org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.250
neo_version_range=[21,)
loader_version_range=[4,)

mod_id=verox_rpg_runestones
mod_name=Verox' RPG Runestones
mod_license=All Rights Reserved
mod_version=1.21.1-0.0.1
mod_group_id=net.veroxuniverse
mod_authors=VeroxUniverse
mod_description=Ancient runestones that link the world - travel with your friends in a bubble of magic.

jei_version=19.5.0.44
geckolib_version=1.21.1:4.8.3
geckolib_version_range=[4.8,)
curios_version_range=[9.0.0,)